{
 "title": "Test",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Airfields",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT * FROM airfields LIMIT 50 "
    }
   ]
  },
  {
   "title": "Moyenne Geo_Score",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT AVG(geo_score) FROM hotspots LIMIT 50 "
    }
   ]
  },
  {
   "title": "Table airfields",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT name, country, longitude, latitude, altitude_estimee_m, climat, timestamp_ingestion, geo_score, source_data FROM airfields LIMIT 50 "
    }
   ]
  },
  {
   "title": "Country par altitude estimée",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "mydb",
     "rawSql": "SELECT country, altitude_estimee_m FROM airports LIMIT 50 "
    }
   ]
  }
 ]
}