{
 "title": "Planes_ma",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Pays",
    "query": "SELECT 'All' AS nom_pays\nUNION\nSELECT DISTINCT nom_pays\nFROM dim_pays\nORDER BY nom_pays;\n"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboard des avions en vol et au sol en temps réel"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "WITH dernier_ts AS (\r\n    SELECT MAX(fk_temps) AS ts\r\n    FROM fait_etat_vol\r\n    WHERE $__timeFilter(fk_temps)\r\n),\r\ndernier_releve AS (\r\n    SELECT \r\n        fev.fk_aeronef,\r\n        fev.velocity,\r\n        fev.geo_altitude,\r\n        COALESCE(fev.on_ground, false) AS on_ground\r\n    FROM fait_etat_vol fev\r\n    JOIN dernier_ts dt ON fev.fk_temps = dt.ts\r\n)\r\nSELECT\r\n    CASE WHEN on_ground = FALSE THEN 'en vol'\r\n         ELSE 'au sol'\r\n    END AS etat,\r\n    COUNT(fk_aeronef) AS \"Nb avions\",\r\n    AVG(velocity) * 3.6 AS \"Vitesse moyenne (km/h)\",\r\n    AVG(geo_altitude) AS \"Altitude géo moyenne (m)\"\r\nFROM dernier_releve\r\nGROUP BY etat;\r\n"
    }
   ]
  },
  {
   "title": "Carte des vols en cours",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "WITH dernier_etat AS (\r\n    SELECT\r\n        fev.fk_aeronef,\r\n        da.pk_aeronef AS aeronef_id,\r\n        dp.latitude,\r\n        dp.longitude,\r\n        dpy.nom_pays AS pays,\r\n        fev.fk_temps AS dernier_temps,\r\n        COALESCE(fev.on_ground, false) AS on_ground,\r\n        fev.geo_altitude AS altitude_geo,\r\n        ROW_NUMBER() OVER (\r\n            PARTITION BY fev.fk_aeronef\r\n            ORDER BY fev.fk_temps DESC\r\n        ) AS rn\r\n    FROM fait_etat_vol fev\r\n    JOIN dim_aeronef da \r\n        ON fev.fk_aeronef = da.pk_aeronef\r\n    JOIN dim_position dp \r\n        ON fev.fk_position = dp.pk_position\r\n    JOIN dim_pays dpy \r\n        ON fev.fk_pays = dpy.pk_pays\r\n    WHERE $__timeFilter(fev.fk_temps)\r\n      AND dp.latitude IS NOT NULL\r\n      AND dp.longitude IS NOT NULL\r\n      AND dp.latitude <> 0\r\n      AND dp.longitude <> 0\r\n)\r\nSELECT\r\n    aeronef_id,\r\n    latitude,\r\n    longitude,\r\n    pays,\r\n    dernier_temps,\r\n    altitude_geo,\r\n    CASE \r\n        WHEN on_ground = true THEN 'au sol'\r\n        ELSE 'en vol'\r\n    END AS etat_sol\r\nFROM dernier_etat\r\nWHERE rn = 1;\r\n"
    }
   ]
  },
  {
   "title": "Nombre d'avions en vol et au sol au cours du temps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 3 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    fev.fk_temps AS timestamp,\r\n    SUM( CASE WHEN COALESCE(fev.on_ground, false) = FALSE THEN 1 ELSE 0 END ) AS en_vol,\r\n    SUM( CASE WHEN COALESCE(fev.on_ground, false) = TRUE  THEN 1 ELSE 0 END ) AS au_sol\r\nFROM fait_etat_vol fev\r\nJOIN dim_aeronef da  ON fev.fk_aeronef = da.pk_aeronef\r\nJOIN dim_position dp ON fev.fk_position  = dp.pk_position\r\nJOIN dim_pays    dpy ON fev.fk_pays       = dpy.pk_pays\r\nWHERE $__timeFilter(fev.fk_temps)\r\nGROUP BY fev.fk_temps\r\nORDER BY fev.fk_temps ASC;\r\n"
    }
   ]
  },
  {
   "title": "Répartition des avions en vol et au sol",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "WITH dernier_ts AS (\r\n    SELECT MAX(fk_temps) AS ts\r\n    FROM fait_etat_vol\r\n    WHERE $__timeFilter(fk_temps)\r\n),\r\ndernier_releve AS (\r\n    SELECT \r\n        fev.fk_aeronef,\r\n        COALESCE(fev.on_ground, false) AS on_ground\r\n    FROM fait_etat_vol fev\r\n    JOIN dernier_ts dt \r\n        ON fev.fk_temps = dt.ts\r\n)\r\nSELECT\r\n    CASE \r\n        WHEN on_ground = FALSE THEN 'en vol'\r\n        ELSE 'au sol'\r\n    END AS etat,\r\n    COUNT(fk_aeronef) AS nb_avions\r\nFROM dernier_releve\r\nGROUP BY etat;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 des Pays d'origine des vols",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT \r\n    fk_pays,\r\n    COUNT(DISTINCT fk_aeronef) AS nb_aeronefs\r\nFROM fait_etat_vol\r\nWHERE $__timeFilter(fk_temps)\r\nGROUP BY fk_pays\r\nORDER BY nb_aeronefs DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Nombre d'avions en montée et en descente",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n    fev.fk_temps AS timestamp,\r\n    SUM( CASE WHEN COALESCE(fev.vertical_rate, 0) > 0 AND COALESCE(fev.on_ground, false) = FALSE THEN 1 ELSE 0 END ) AS en_montee,\r\n    SUM( CASE WHEN COALESCE(fev.vertical_rate, 0) < 0 AND COALESCE(fev.on_ground, false) = FALSE THEN 1 ELSE 0 END ) AS en_descente\r\nFROM fait_etat_vol fev\r\nJOIN dim_aeronef da  ON fev.fk_aeronef = da.pk_aeronef\r\nJOIN dim_position dp ON fev.fk_position  = dp.pk_position\r\nJOIN dim_pays    dpy ON fev.fk_pays       = dpy.pk_pays\r\nWHERE $__timeFilter(fev.fk_temps)\r\nGROUP BY fev.fk_temps\r\nORDER BY fev.fk_temps ASC;\r\n"
    }
   ]
  },
  {
   "title": "Nombre d'avion par géo altitude (m)",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "WITH dernier_ts AS (\r\n    SELECT MAX(fk_temps) AS ts\r\n    FROM fait_etat_vol\r\n    WHERE $__timeFilter(fk_temps)\r\n),\r\ndernier_releve AS (\r\n    SELECT \r\n        fev.fk_aeronef,\r\n        CAST(fev.velocity * 3.6 AS INTEGER) AS vitesse_kmh,  -- vitesse en entier\r\n        CAST(fev.geo_altitude AS INTEGER) AS altitude_geo,   -- altitude en entier\r\n        COALESCE(fev.on_ground, false) AS on_ground\r\n    FROM fait_etat_vol fev\r\n    JOIN dernier_ts dt ON fev.fk_temps = dt.ts\r\n)\r\nSELECT\r\n    FLOOR(altitude_geo / 500) * 500 AS altitude_bucket,\r\n    COUNT(DISTINCT fk_aeronef) AS nb_avions_uniques\r\nFROM dernier_releve\r\nWHERE on_ground = FALSE\r\nGROUP BY altitude_bucket\r\nORDER BY altitude_bucket;\r\n"
    }
   ]
  }
 ]
}